## CHANGE this to the name of your plugin.
name: MagicaeMechanica

## CHANGE this to your username.
author: Apeiros-46B

## CHANGE this to a meaningful but short description of your plugin.
description: A Slimefun4 addon that aims to bridge the gap between magic and technology.

## CHANGE this to the path of the class that extends JavaPlugin.
main: xyz.apeiros.magicaemechanica.MagicaeMechanica

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/Apeiros-46B/MagicaeMechanica

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.19

## Marks Slimefun and AlchimiaVitae as dependencies
depend:
- Slimefun
- AlchimiaVitae

## Softdepends FoxyMachines and SlimefunWarfare for overlapping items
softdepend:
- FoxyMachines
- SlimefunWarfare